bert_model:
  model_id: sentence-transformers/all-MiniLM-L12-v2
  threshold: 0.6
  use_cpu: true
semantic_cache:
  enabled: true
  similarity_threshold: 0.8
  max_entries: 1000
  ttl_seconds: 3600
gpu_config:
  flops: 312000000000000  # 312e12 fp16
  hbm: 2000000000000      # 2e12 (2 TB/s)
  description: "A100-80G" # https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-us-nvidia-1758950-r4-web.pdf
model_config:
  phi4:
    param_count: 14000000000  # 14B parameters https://huggingface.co/microsoft/phi-4
    batch_size: 512.0  # vLLM default batch size
    context_size: 16384.0 # based on https://huggingface.co/microsoft/phi-4
  gemma3:27b:
    param_count: 27000000000  # 27B parameters (base version)
    batch_size: 512.0
    context_size: 16384.0
  "mistral-small3.1":
    param_count: 22000000000
    batch_size: 512.0
    context_size: 16384.0
# Classifier configuration for text classification (legacy - replaced by dual_classifier)
classifier:
  model_id: "HuaminChen/category_classifier_linear_model"
  threshold: 0.1
  use_cpu: true
  load_aware: false
  category_mapping_path: "config/category_mapping.json"    
categories:
- name: Math
  model_scores:
  - model: phi4
    score: 1.0
  - model: mistral-small3.1
    score: 0.8
  - model: gemma3:27b
    score: 0.6
- name: History
  model_scores:
  - model: mistral-small3.1
    score: 0.8
  - model: phi4
    score: 0.6
  - model: gemma3:27b
    score: 0.4
- name: Health
  model_scores:
  - model: gemma3:27b
    score: 0.8
  - model: phi4
    score: 0.8
  - model: mistral-small3.1
    score: 0.6
- name: Programming
  model_scores:
  - model: gemma3:27b
    score: 0.6
  - model: mistral-small3.1
    score: 0.6
  - model: phi4
    score: 0.4
- name: General
  model_scores:
  - model: gemma3:27b
    score: 0.8
  - model: phi4
    score: 0.6
  - model: mistral-small3.1
    score: 0.6
default_model: mistral-small3.1

# Dual classifier configuration - handles both category classification AND PII detection
dual_classifier:
  enabled: true
  model_path: "finetune-model"  # Path to the trained enhanced model that does both tasks
  use_cpu: true
  # PII detection settings for the dual classifier
  block_on_pii: false      # Whether to block requests containing PII
  sanitize_enabled: true   # Whether to sanitize PII in responses
  pii_threshold: 0.5       # Threshold for PII detection confidence
